---
name: microbosh-aws-us-east-1

env:
  bosh:
    password: $6$salt$password

logging:
  level: DEBUG

network:
  type: dynamic
  ip: IPADDRESS

resources:
  cloud_properties:
    instance_type: m1.small

cloud:
  plugin: aws
  properties:
    aws:
      access_key_id:     ACCESS_KEY_ID
      secret_access_key: SECRET_ACCESS_KEY
      default_key_name: fog_default
      default_security_groups: ["default"]
      ec2_private_key: /home/vcap/.ssh/id_rsa